### ISSUE TITLE
Cookie mismatch betwen write and read packet

### ISSUE THREAD

**Issue by nvasudevan** [florentchauveau/go-kamailio-binrpc#12]
Hello,

I seem to be hitting an issue with the cookie mismatch between `WritePacket` and `ReadPacket` from the fetchBINRPC (https://github.com/florentchauveau/kamailio_exporter/blob/master/collector.go#L569) in certain cases, in particular when the cookie value is at the lower end of the uint32 range. Here is an example of a cookie with value **10038690**.

The `WritePacket` within binrpc returns the cookie byte array **[0 153 45 162]**, the 
header bytes written to the IO writer is: **{[161 3 19 0 153 45 162] 0 0}**

However, when we subsequently do a `ReadPacket`, which then invokes the `ReadHeader`,
the resulting cookie is derived as **[153 45 162]**, It seems the calculation results in a 
mismatch with the length of the cookie, possibly here:

https://github.com/florentchauveau/go-kamailio-binrpc/blob/master/binrpc.go#L279-L280

In the case of my example cookie, the first 2 bytes read were: **[161 18]**. This results in the 
`sizeOfLength`(=1) and `sizeOfCookie`(=3), and the cookie byte array evaluates to **[153, 45, 162]**.
This causes validation failure here (as **[153, 45, 162]** != **[0 153 45 162]**): 

https://github.com/florentchauveau/go-kamailio-binrpc/blob/master/binrpc.go#L431 

The validation failure causes the Prometheus to mark Kamailio as down which then triggers alerts. Are you able to provide any pointers as to what is the best way to resolve this? At present, I don't fully understand the second byte within the buffer when a read is invoked in the `ReadHeader` (https://github.com/florentchauveau/kamailio_exporter/blob/master/collector.go#L569), as that is the basis of length and cookie calculation. There are other options, we only look at the higher end of the uint32 range for the cookie. I haven't tried this, so this is a suggestion.

**Comment by florentchauveau** [comment]
Hello @nvasudevan, I can reproduce the issue.

I will work on this asap. Thanks for the pointers!

**Comment by florentchauveau** [comment]
Hello again,

Your analysis was correct. There were actually two bugs:
* integer encoding was not optimal for integer in range 17..24 bits (they were always encoded in 32 bits instead of 24)
* cookie comparison was based on byte sequence diff, instead of actual integer value

For example, a cookie value of 0x7FFFFD was encoded in 32bits, so: [00 7F FF FD], instead of more optimal [7F FF FD]. Kamailio on the other hand, replies with the optimal value: 0x7FFFFD. So when we were comparing the sequence of bytes: [00 7F FF FD] != [7F FF FD] hence the cookie mismatch.

I have fixed both things with in the v3 release. Integers that fit in 3 bytes are now encoded with 3 bytes. And the cookie is now exposed as an uint32, not a sequence of bytes.
